apiVersion: v1
kind: Service
metadata:
  name: clixluster-redis-svc
  labels:
    app: clixluster-redis
spec:
  type: ClusterIP # פנימי בלבד! אנחנו לא רוצים ש-Redis יהיה חשוף לאינטרנט או מחוץ לקלאסטר
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: clixluster-redis