apiVersion: v1
kind: Service
metadata:
  name: clixluster-frontend-svc
  namespace: clixluster
spec:
  type: NodePort # מאפשר גישה קלה בקלאסטר לוקאלי
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
    protocol: TCP
  selector:
    app: clixluster-frontend