apiVersion: apps/v1
kind: Deployment
metadata:
  name: clixluster-frontend
  namespace: clixluster
  labels:
    app: clixluster-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clixluster-frontend
  template:
    metadata:
      labels:
        app: clixluster-frontend
    spec:
      containers:
      - name: frontend
        image: ido1t7/clixluster-frontend:v1.26
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
