apiVersion: v1
kind: Service
metadata:
  name: clixluster-redis-svc
  namespace: clixluster
  labels:
    app: clixluster-redis
spec:
  type: ClusterIP # פנימי בלבד! לא חושפים את Redis מחוץ לקלאסטר
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: clixluster-redis
